# Use the official Elixir image as the base image
FROM docker.io/library/elixir:1.20.3-otp-29-alpine@sha256:8e4dcf7e98d3e06f4a6f56ed40e65b33b6bd84b0779698c8562d61d06218f314 AS build

# Install build dependencies
RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache \
      build-base \
      git \
      bash \
      postgresql-client

# Set the working directory inside the container
WORKDIR /app

# Install Hex and Rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Set environment to prod for building
ENV MIX_ENV=prod

# Copy over the necessary application files and directories
COPY config/ config/
COPY lib/ lib/
COPY priv/ priv/
COPY assets/ assets/
COPY mix.exs .
COPY mix.lock .

# Fetch the application dependencies and compile the app
RUN mix deps.get --only prod && \
    mix deps.compile

# Compile and digest static assets.
RUN mix assets.deploy

# Build the release
RUN mix release

# Start a new build stage to create a cleaner final image
FROM docker.io/library/alpine:3.22.5@sha256:14358309a308569c32bdc37e2e0e9694be33a9d99e68afb0f5ff33cc1f695dce

# Install runtime dependencies
RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache \
      bash \
      openssl \
      ncurses-libs \
      postgresql-client \
      libstdc++

RUN addgroup -S app && adduser -S -G app -h /app app

# Set the working directory inside the container
WORKDIR /app

# Copy the release from the build stage
COPY --from=build --chown=app:app /app/_build/prod/rel/website_45s_v3 ./

# Copy the entrypoint script to the container
COPY --chown=app:app prod_entrypoint.sh /app/entrypoint.sh

# Make the script executable
RUN chmod +x /app/entrypoint.sh

USER app

# Expose port 4000 for the app
EXPOSE 4000

# Use the entrypoint script to run migrations and then start the Phoenix server
ENTRYPOINT ["/app/entrypoint.sh"]
