version: '3'

services:
  web:
    image: website_45s_v3
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dataBaseWaterBottle
      - POSTGRES_DB=website_45s_v3_prod

volumes:
  db_data:
