services:
  web:
    image: thwar/fortyfives.net:latest
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  db_data:
