import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
#
# `force_ssl` is the single owner of HTTPS redirects and the
# Strict-Transport-Security header (nginx.conf deliberately does not add one).
# The app sits behind nginx/Cloudflare, so the scheme is read from
# X-Forwarded-Proto. `exclude` lets the in-container Docker HEALTHCHECK hit
# http://127.0.0.1:4000/healthz without being redirected. See `Plug.SSL` for
# the option names.
config :website_45s_v3, Website45sV3Web.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [
    hsts: true,
    expires: 31_536_000,
    subdomains: true,
    rewrite_on: [:x_forwarded_proto],
    exclude: ["localhost", "127.0.0.1"]
  ]

config :website_45s_v3, :secure_cookies, true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
